/**:
  ros__parameters:
    inspection_points:
      text:   [ "000",    "100",    "200",    "300",    "400",]
      x:      [  0.000,    0.407,   -0.080,    0.373,    2.003,]
      y:      [  0.000,    1.330,    0.251,   -1.410,   -1.296,]
      theta:  [  0.000,    0.048,    2.372,   -0.631,   -1.050,]