/**:
  ros__parameters:
    inspection_points:
      text:   [ "100",    "200",    "300",    "400",]
      x:      [ 0.0,      -0.049,   0.0,      -0.64,]
      y:      [ 0.0,      0.427,    0.0,      0.7,  ]
      theta:  [ 0.0,      2.372,    0.0,      2.093,]